-- =============================================================================
-- SECTION 4.23: MORE TRANSFORMATIONS - SUBSET COLUMNS & AUTO-INCREMENT IDs
-- =============================================================================
--
-- OBJECTIVE:
--   Learn how to load data into a SUBSET of target table columns, and how
--   to use Snowflake's AUTOINCREMENT feature for surrogate key generation.
--
-- WHAT YOU WILL LEARN:
--   1. Loading into specific columns using COPY INTO table(col1, col2)
--   2. Skipping columns during load (they get NULL or default values)
--   3. AUTOINCREMENT for automatic surrogate key generation
--   4. Combining column subsetting with $N positional references
--
-- KEY INTERVIEW CONCEPTS:
--   - COPY INTO table(col1, col2) to load only specific columns
--   - AUTOINCREMENT (start, increment) for surrogate keys
--   - Omitting auto-increment columns from COPY column list
--   - Unspecified columns receive NULL or their DEFAULT value
--
-- AUTOINCREMENT vs IDENTITY (CONCEPT GAP FILLED):
--   AUTOINCREMENT and IDENTITY are synonyms in Snowflake. Both work:
--     - col NUMBER AUTOINCREMENT START 1 INCREMENT 1
--     - col NUMBER IDENTITY(1, 1)
--   Unlike traditional databases, Snowflake autoincrement is NOT guaranteed
--   to be gap-free. Gaps can occur due to failed transactions or parallel loads.
--
-- SEQUENCES (CONCEPT GAP FILLED):
--   For more control over auto-generated IDs, use SEQUENCE objects:
--     CREATE SEQUENCE my_seq START = 1 INCREMENT = 1;
--     INSERT INTO table (id, name) VALUES (my_seq.NEXTVAL, 'Alice');
--   Sequences can be shared across tables and have more configuration options.
-- =============================================================================


-- =============================================
-- EXAMPLE 4: Loading into a subset of columns
-- =============================================
-- Create a table with 4 columns, but only load 2 of them.
-- The unloaded columns (AMOUNT, PROFITABLE_FLAG) will be NULL.

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_EX (
    ORDER_ID        VARCHAR(30),
    AMOUNT          INT,
    PROFIT          INT,
    PROFITABLE_FLAG VARCHAR(30)
);

-- Specify target columns in COPY INTO table(col1, col2)
-- Only ORDER_ID and PROFIT are loaded; AMOUNT and PROFITABLE_FLAG remain NULL.

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_EX (ORDER_ID, PROFIT)
    FROM (
        SELECT
            s.$1,       -- Maps to ORDER_ID (1st column in target list)
            s.$3        -- Maps to PROFIT   (2nd column in target list)
        FROM @MANAGE_DB.external_stages.aws_stage s
    )
    file_format = (type = csv field_delimiter = ',' skip_header = 1)
    files = ('OrderDetails.csv');

-- IMPORTANT: The SELECT column order must match the COPY column list order.
--   s.$1 -> ORDER_ID (first in list), s.$3 -> PROFIT (second in list)

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_EX;
-- Expected: ORDER_ID and PROFIT populated, AMOUNT and PROFITABLE_FLAG are NULL


-- =============================================
-- EXAMPLE 5: AUTOINCREMENT for surrogate keys
-- =============================================
-- Create a table where ORDER_ID is auto-generated by Snowflake.

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_EX (
    ORDER_ID        NUMBER AUTOINCREMENT START 1 INCREMENT 1,  -- Auto-generated ID
    AMOUNT          INT,
    PROFIT          INT,
    PROFITABLE_FLAG VARCHAR(30)
);

-- AUTOINCREMENT SYNTAX:
--   AUTOINCREMENT                     -- Defaults: start=1, increment=1
--   AUTOINCREMENT START 1 INCREMENT 1 -- Explicit start and step
--   IDENTITY(1, 1)                    -- Alternate syntax (same behavior)

-- Load data WITHOUT specifying ORDER_ID (Snowflake generates it).
-- Note: COPY column list includes only PROFIT and AMOUNT.

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_EX (PROFIT, AMOUNT)
    FROM (
        SELECT
            s.$2,       -- Maps to PROFIT (1st in target list)
            s.$3        -- Maps to AMOUNT (2nd in target list)
        FROM @MANAGE_DB.external_stages.aws_stage s
    )
    file_format = (type = csv field_delimiter = ',' skip_header = 1)
    files = ('OrderDetails.csv');

-- CRITICAL: Do NOT include the AUTOINCREMENT column in the COPY column list.
-- Snowflake will automatically generate sequential values for ORDER_ID.

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_EX WHERE ORDER_ID > 15;


-- =============================================
-- Cleanup
-- =============================================
DROP TABLE OUR_FIRST_DB.PUBLIC.ORDERS_EX;


-- =============================================================================
-- CONCEPT GAP: DEFAULT VALUES IN COPY
-- =============================================================================
-- Besides AUTOINCREMENT, you can use DEFAULT values for columns not in COPY:
--
-- CREATE TABLE orders (
--     id          NUMBER AUTOINCREMENT,
--     order_date  DATE DEFAULT CURRENT_DATE(),    -- Auto-fills with today
--     status      VARCHAR(20) DEFAULT 'NEW',      -- Auto-fills with 'NEW'
--     amount      INT
-- );
--
-- COPY INTO orders (amount)
--     FROM (SELECT s.$1 FROM @stage s)
--     file_format = (...);
-- -- Result: id=auto, order_date=today, status='NEW', amount=loaded value
--
-- INTERVIEW TIP: DEFAULT values only apply when the column is omitted from
-- the COPY column list. If you include the column and the CSV has NULL,
-- the value will be NULL (not the default).
-- =============================================================================
